### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by cspoonerKRHS** [KRHS-GameProgramming-2015/King-of-the-Pile#1]
Game crashes when predator moves and you eat poison food.

Traceback (most recent call last):
  File "KingOTP.py", line 113, in <module>
    player.grow(first)
  File "/home/spooner/Docs/Kearsarge/Game Programming/Game 1 2015/King of the Pile/Player.py", line 80, in grow
    self.accx = self.accControlx/(self.mass/50)
ZeroDivisionError: float division by zero

Version:  12a14a0  

check masses before the error happens and end the game properly

**Comment by rcnerd** [comment]
Still present... If not addressed by 1-6-16 I will remind Edward. If not addressed by 1-13-16 will handle myself

**Comment by Xward555** [comment]
Sorry, I was planning to get mr.spooner to help me on this, but he's been
sick

**Comment by cspoonerKRHS** [comment]
I should be in tomorrow and will help then.
